### ISSUE TITLE
Allow members to bypass whitelist

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [twbs/savage#30]
Any thought given to creating a new setting that allows members to bypass the whitelist check?  Our organization is fairly large.  We trust our devs enough to submit Pull Requests with any change, but not enough to give them write access to the repo.  :smile: 

I'm comfortable making a change similar to the following in our instance, but was curious if you'd be interested in a PR back?

Snippet from https://github.com/twbs/savage/blob/master/src/main/scala/com/getbootstrap/savage/server/PullRequestEventHandler.scala#L109

```
...
case Success(affectedFiles) => {
  log.debug("Files affected by {}: {}", prNum, affectedFiles)
  if (areSafe(affectedFiles) || (trustedCanBypassWhitelistSetting && isTrusted(pr.user))) {
    if (areInteresting(affectedFiles)) {
...
```

**Comment by cvrebert** [comment]
Fine by me. I'm okay with just making this the default, no need for a `trustedCanBypassWhitelistSetting`.
